let strip_1: neopixel.Strip = null
let strip_2: neopixel.Strip = null
let strip_3: neopixel.Strip = null
let strip_4: neopixel.Strip = null
basic.forever(function () {
    maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 30)
    strip_1 = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)
    strip_1.setBrightness(10)
    strip_1.setPixelColor(0, neopixel.colors(NeoPixelColors.White))
    strip_1.setPixelColor(1, neopixel.colors(NeoPixelColors.Black))
    strip_1.setPixelColor(2, neopixel.colors(NeoPixelColors.Black))
    strip_1.setPixelColor(3, neopixel.colors(NeoPixelColors.White))
    music.playMelody("E B C5 A B G A F ", 120)
    strip_1.show()
    basic.pause(500)
    maqueen.motorStop(maqueen.Motors.All)
    maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CCW, 30)
    strip_2 = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)
    strip_2.setBrightness(10)
    strip_2.setPixelColor(0, neopixel.colors(NeoPixelColors.Black))
    strip_2.setPixelColor(1, neopixel.colors(NeoPixelColors.Red))
    strip_2.setPixelColor(2, neopixel.colors(NeoPixelColors.Red))
    strip_2.setPixelColor(3, neopixel.colors(NeoPixelColors.Black))
    strip_2.show()
    music.playTone(262, music.beat(BeatFraction.Whole))
    music.playTone(262, music.beat(BeatFraction.Whole))
    music.playTone(262, music.beat(BeatFraction.Whole))
    music.playTone(262, music.beat(BeatFraction.Whole))
    basic.pause(100)
    maqueen.motorStop(maqueen.Motors.All)
    maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 80)
    maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 80)
    strip_3 = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)
    strip_3.setBrightness(10)
    strip_3.setPixelColor(0, neopixel.colors(NeoPixelColors.Orange))
    strip_3.setPixelColor(1, neopixel.colors(NeoPixelColors.Orange))
    strip_3.setPixelColor(2, neopixel.colors(NeoPixelColors.Black))
    strip_3.setPixelColor(3, neopixel.colors(NeoPixelColors.Black))
    strip_3.show()
    basic.pause(100)
    music.playMelody("C5 B A G F E D C ", 120)
    maqueen.motorStop(maqueen.Motors.All)
    maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 80)
    maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 80)
    strip_4 = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)
    strip_4.setBrightness(10)
    strip_4.setPixelColor(0, neopixel.colors(NeoPixelColors.Black))
    strip_4.setPixelColor(1, neopixel.colors(NeoPixelColors.Black))
    strip_4.setPixelColor(2, neopixel.colors(NeoPixelColors.Orange))
    strip_4.setPixelColor(3, neopixel.colors(NeoPixelColors.Orange))
    music.playMelody("E B F A G G A F ", 120)
    strip_4.show()
    basic.pause(100)
    maqueen.motorStop(maqueen.Motors.All)
})
basic.forever(function () {
	
})
